In [14]:
%pip install pandas

Collecting pandas
  Using cached pandas-3.0.0-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin\appdata\local\spyder-6\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\local\spyder-6\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\admin\appdata\local\spyder-6\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\local\spyder-6\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.0-cp311-cp311-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB 262.6 kB/s eta 0:00:38
   ---------------------------------------- 0.1/9.9 MB 409.6 kB/s eta 0:00:24
   ---------------------------------------- 0.1/9.9 MB 435.7 kB/s eta 0:00:23
   ---------------------------------------- 0.1/9.9 MB 374.1 kB/s eta 0:00:27
   ---------------------------------------- 0.1/9.9 MB 400.9 kB/s eta 0:00:25
    --------------------------------------- 0.2/9.9 MB 437.1 kB/s eta 0:00:23
    --------------------------------------- 0.2/9.9 MB 456.4 kB/s eta 0:00:22
    --------------------------------------- 0.2/9.9 MB 456.4 kB/s eta 0:00:22
    --------------------------------------- 0.2/9.9 MB 384.3 kB/s eta 0:00:26
    --------------------------------------- 0.2/9.9 MB 384.3 kB/s eta 0:00:26
    --------------------------------------- 0.2/9.9 MB 384.3 kB/s eta 0:00:26
   - -------------------------------------- 0.3/9.9 MB 383.4 kB/s eta 0:00:26
   - -------------------------------------- 0.3/9.9 MB 383.4 kB/s eta 0:00:26
   - -------------------------------------- 0.3/9.9 MB 383.4 kB/s eta 0:00:26
   - -------------------------------------- 0.3/9.9 MB 334.2 kB/s eta 0:00:29
   - -------------------------------------- 0.3/9.9 MB 371.0 kB/s eta 0:00:26
   - -------------------------------------- 0.3/9.9 MB 381.5 kB/s eta 0:00:26
   - -------------------------------------- 0.4/9.9 MB 376.1 kB/s eta 0:00:26
   - -------------------------------------- 0.4/9.9 MB 403.1 kB/s eta 0:00:24
   - -------------------------------------- 0.5/9.9 MB 414.6 kB/s eta 0:00:23
   - -------------------------------------- 0.5/9.9 MB 424.7 kB/s eta 0:00:23
   -- ------------------------------------- 0.5/9.9 MB 428.1 kB/s eta 0:00:22
   -- ------------------------------------- 0.6/9.9 MB 451.1 kB/s eta 0:00:21
   -- ------------------------------------- 0.6/9.9 MB 448.1 kB/s eta 0:00:21
   -- ------------------------------------- 0.6/9.9 MB 448.1 kB/s eta 0:00:21
   -- ------------------------------------- 0.6/9.9 MB 434.3 kB/s eta 0:00:22
   -- ------------------------------------- 0.6/9.9 MB 456.4 kB/s eta 0:00:21
   -- ------------------------------------- 0.6/9.9 MB 456.4 kB/s eta 0:00:21
   -- ------------------------------------- 0.7/9.9 MB 453.1 kB/s eta 0:00:21
   -- ------------------------------------- 0.7/9.9 MB 457.4 kB/s eta 0:00:21
   --- ------------------------------------ 0.8/9.9 MB 469.0 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/9.9 MB 469.0 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/9.9 MB 468.0 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/9.9 MB 464.6 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/9.9 MB 468.1 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/9.9 MB 468.1 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/9.9 MB 468.1 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/9.9 MB 433.5 kB/s eta 0:00:21
   --- ------------------------------------ 0.9/9.9 MB 459.4 kB/s eta 0:00:20
   --- ------------------------------------ 1.0/9.9 MB 468.9 kB/s eta 0:00:20
   --- ------------------------------------ 1.0/9.9 MB 463.2 kB/s eta 0:00:20
   ---- ----------------------------------- 1.0/9.9 MB 467.4 kB/s eta 0:00:19
   ---- ----------------------------------- 1.1/9.9 MB 484.5 kB/s eta 0:00:19
   ---- ----------------------------------- 1.1/9.9 MB 488.1 kB/s eta 0:00:19
   ---- ----------------------------------- 1.1/9.9 MB 489.3 kB/s eta 0:00:18
   ---- ----------------------------------- 1.2/9.9 MB 493.7 kB/s eta 0:00:18
   ---- ----------------------------------- 1.2/9.9 MB 501.1 kB/s eta 0:00:18
   ----- ---------------------------------- 1.2/9.9 MB 504.2 kB/s eta 0:00:18
   ----- ---------------------------------- 1.3/9.9 MB 513.5 kB/s eta 0:00:17
   ----- ---------------------------------- 1.3/9.9 MB 513.5 kB/s eta 0:00:17
   ----- ---------------------------------- 1.3/9.9 MB 513.5 kB/s eta 0:00:17
   ----- ---------------------------------- 1.3/9.9 MB 513.5 kB/s eta 0:00:17
   ----- ---------------------------------- 1.3/9.9 MB 513.5 kB/s eta 0:00:17
   ----- ---------------------------------- 1.3/9.9 MB 491.6 kB/s eta 0:00:18
   ----- ---------------------------------- 1.4/9.9 MB 498.1 kB/s eta 0:00:18
   ----- ---------------------------------- 1.4/9.9 MB 497.9 kB/s eta 0:00:18
   ----- ---------------------------------- 1.4/9.9 MB 503.3 kB/s eta 0:00:17
   ----- ---------------------------------- 1.4/9.9 MB 503.3 kB/s eta 0:00:17
   ----- ---------------------------------- 1.4/9.9 MB 503.3 kB/s eta 0:00:17
   ----- ---------------------------------- 1.4/9.9 MB 503.3 kB/s eta 0:00:17
   ----- ---------------------------------- 1.4/9.9 MB 503.3 kB/s eta 0:00:17
   ----- ---------------------------------- 1.4/9.9 MB 503.3 kB/s eta 0:00:17
   ------ --------------------------------- 1.5/9.9 MB 490.8 kB/s eta 0:00:18
   ------ --------------------------------- 1.5/9.9 MB 490.8 kB/s eta 0:00:18
   ------ --------------------------------- 1.6/9.9 MB 478.9 kB/s eta 0:00:18
   ------ --------------------------------- 1.6/9.9 MB 477.5 kB/s eta 0:00:18
   ------ --------------------------------- 1.6/9.9 MB 486.2 kB/s eta 0:00:17
   ------ --------------------------------- 1.6/9.9 MB 486.2 kB/s eta 0:00:17
   ------ --------------------------------- 1.7/9.9 MB 490.1 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 498.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 498.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 498.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 498.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 498.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 498.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 498.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 498.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 498.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 498.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 498.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 498.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 498.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 498.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 498.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 498.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 498.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 498.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 498.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 498.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 498.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 498.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 498.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 498.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 498.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.7/9.9 MB 383.2 kB/s eta 0:00:22
   ------- -------------------------------- 1.7/9.9 MB 383.2 kB/s eta 0:00:22
   ------- -------------------------------- 1.7/9.9 MB 383.2 kB/s eta 0:00:22
   ------- -------------------------------- 1.7/9.9 MB 383.2 kB/s eta 0:00:22
   ------- -------------------------------- 1.8/9.9 MB 376.7 kB/s eta 0:00:22
   ------- -------------------------------- 1.8/9.9 MB 376.7 kB/s eta 0:00:22
   ------- -------------------------------- 1.8/9.9 MB 367.8 kB/s eta 0:00:22
   ------- -------------------------------- 1.8/9.9 MB 367.8 kB/s eta 0:00:22
   ------- -------------------------------- 1.8/9.9 MB 367.8 kB/s eta 0:00:22
   ------- -------------------------------- 1.8/9.9 MB 367.8 kB/s eta 0:00:22
   ------- -------------------------------- 1.8/9.9 MB 361.6 kB/s eta 0:00:23
   ------- -------------------------------- 1.8/9.9 MB 361.6 kB/s eta 0:00:23
   ------- -------------------------------- 1.8/9.9 MB 361.6 kB/s eta 0:00:23
   ------- -------------------------------- 1.8/9.9 MB 361.6 kB/s eta 0:00:23
   ------- -------------------------------- 1.9/9.9 MB 362.1 kB/s eta 0:00:23
   ------- -------------------------------- 1.9/9.9 MB 362.1 kB/s eta 0:00:23
   ------- -------------------------------- 1.9/9.9 MB 359.7 kB/s eta 0:00:23
   ------- -------------------------------- 1.9/9.9 MB 359.4 kB/s eta 0:00:23
   ------- -------------------------------- 1.9/9.9 MB 361.1 kB/s eta 0:00:22
   ------- -------------------------------- 1.9/9.9 MB 361.1 kB/s eta 0:00:22
   ------- -------------------------------- 1.9/9.9 MB 361.1 kB/s eta 0:00:22
   -------- ------------------------------- 2.0/9.9 MB 357.3 kB/s eta 0:00:23
   -------- ------------------------------- 2.0/9.9 MB 357.3 kB/s eta 0:00:23
   -------- ------------------------------- 2.1/9.9 MB 363.1 kB/s eta 0:00:22
   -------- ------------------------------- 2.1/9.9 MB 362.9 kB/s eta 0:00:22
   -------- ------------------------------- 2.1/9.9 MB 362.9 kB/s eta 0:00:22
   -------- ------------------------------- 2.1/9.9 MB 362.9 kB/s eta 0:00:22
   -------- ------------------------------- 2.1/9.9 MB 354.8 kB/s eta 0:00:22
   -------- ------------------------------- 2.1/9.9 MB 356.3 kB/s eta 0:00:22
   -------- ------------------------------- 2.1/9.9 MB 356.3 kB/s eta 0:00:22
   -------- ------------------------------- 2.1/9.9 MB 353.4 kB/s eta 0:00:22
   -------- ------------------------------- 2.2/9.9 MB 358.3 kB/s eta 0:00:22
   -------- ------------------------------- 2.2/9.9 MB 359.6 kB/s eta 0:00:22
   -------- ------------------------------- 2.2/9.9 MB 361.1 kB/s eta 0:00:22
   -------- ------------------------------- 2.2/9.9 MB 361.1 kB/s eta 0:00:22
   --------- ------------------------------ 2.3/9.9 MB 357.9 kB/s eta 0:00:22
   --------- ------------------------------ 2.3/9.9 MB 358.5 kB/s eta 0:00:22
   --------- ------------------------------ 2.3/9.9 MB 357.5 kB/s eta 0:00:22
   --------- ------------------------------ 2.3/9.9 MB 356.3 kB/s eta 0:00:22
   --------- ------------------------------ 2.3/9.9 MB 353.6 kB/s eta 0:00:22
   --------- ------------------------------ 2.3/9.9 MB 355.0 kB/s eta 0:00:22
   --------- ------------------------------ 2.3/9.9 MB 355.0 kB/s eta 0:00:22
   --------- ------------------------------ 2.4/9.9 MB 353.0 kB/s eta 0:00:22
   --------- ------------------------------ 2.4/9.9 MB 352.8 kB/s eta 0:00:22
   --------- ------------------------------ 2.4/9.9 MB 352.8 kB/s eta 0:00:22
   --------- ------------------------------ 2.4/9.9 MB 350.3 kB/s eta 0:00:22
   --------- ------------------------------ 2.4/9.9 MB 350.3 kB/s eta 0:00:22
   --------- ------------------------------ 2.4/9.9 MB 350.3 kB/s eta 0:00:22
   --------- ------------------------------ 2.4/9.9 MB 345.3 kB/s eta 0:00:22
   --------- ------------------------------ 2.4/9.9 MB 345.2 kB/s eta 0:00:22
   --------- ------------------------------ 2.4/9.9 MB 345.2 kB/s eta 0:00:22
   --------- ------------------------------ 2.4/9.9 MB 342.8 kB/s eta 0:00:22
   --------- ------------------------------ 2.4/9.9 MB 342.8 kB/s eta 0:00:22
   --------- ------------------------------ 2.5/9.9 MB 342.7 kB/s eta 0:00:22
   ---------- ----------------------------- 2.5/9.9 MB 341.1 kB/s eta 0:00:22
   ---------- ----------------------------- 2.5/9.9 MB 340.3 kB/s eta 0:00:22
   ---------- ----------------------------- 2.5/9.9 MB 340.2 kB/s eta 0:00:22
   ---------- ----------------------------- 2.5/9.9 MB 340.2 kB/s eta 0:00:22
   ---------- ----------------------------- 2.5/9.9 MB 339.4 kB/s eta 0:00:22
   ---------- ----------------------------- 2.5/9.9 MB 337.9 kB/s eta 0:00:22
   ---------- ----------------------------- 2.6/9.9 MB 337.8 kB/s eta 0:00:22
   ---------- ----------------------------- 2.6/9.9 MB 336.4 kB/s eta 0:00:22
   ---------- ----------------------------- 2.6/9.9 MB 336.4 kB/s eta 0:00:22
   ---------- ----------------------------- 2.6/9.9 MB 335.6 kB/s eta 0:00:22
   ---------- ----------------------------- 2.6/9.9 MB 334.9 kB/s eta 0:00:22
   ---------- ----------------------------- 2.6/9.9 MB 334.9 kB/s eta 0:00:22
   ---------- ----------------------------- 2.6/9.9 MB 333.6 kB/s eta 0:00:22
   ---------- ----------------------------- 2.7/9.9 MB 334.8 kB/s eta 0:00:22
   ---------- ----------------------------- 2.7/9.9 MB 334.8 kB/s eta 0:00:22
   ---------- ----------------------------- 2.7/9.9 MB 333.4 kB/s eta 0:00:22
   ---------- ----------------------------- 2.7/9.9 MB 332.1 kB/s eta 0:00:22
   ---------- ----------------------------- 2.7/9.9 MB 333.4 kB/s eta 0:00:22
   ----------- ---------------------------- 2.7/9.9 MB 332.7 kB/s eta 0:00:22
   ----------- ---------------------------- 2.7/9.9 MB 332.7 kB/s eta 0:00:22
   ----------- ---------------------------- 2.7/9.9 MB 332.7 kB/s eta 0:00:22
   ----------- ---------------------------- 2.7/9.9 MB 329.5 kB/s eta 0:00:22
   ----------- ---------------------------- 2.7/9.9 MB 329.5 kB/s eta 0:00:22
   ----------- ---------------------------- 2.8/9.9 MB 328.9 kB/s eta 0:00:22
   ----------- ---------------------------- 2.8/9.9 MB 328.9 kB/s eta 0:00:22
   ----------- ---------------------------- 2.8/9.9 MB 328.9 kB/s eta 0:00:22
   ----------- ---------------------------- 2.8/9.9 MB 328.9 kB/s eta 0:00:22
   ----------- ---------------------------- 2.8/9.9 MB 326.5 kB/s eta 0:00:22
   ----------- ---------------------------- 2.8/9.9 MB 326.5 kB/s eta 0:00:22
   ----------- ---------------------------- 2.8/9.9 MB 324.8 kB/s eta 0:00:22
   ----------- ---------------------------- 2.8/9.9 MB 324.8 kB/s eta 0:00:22
   ----------- ---------------------------- 2.9/9.9 MB 324.2 kB/s eta 0:00:22
   ----------- ---------------------------- 2.9/9.9 MB 324.2 kB/s eta 0:00:22
   ----------- ---------------------------- 2.9/9.9 MB 323.7 kB/s eta 0:00:22
   ----------- ---------------------------- 2.9/9.9 MB 323.1 kB/s eta 0:00:22
   ----------- ---------------------------- 2.9/9.9 MB 322.6 kB/s eta 0:00:22
   ----------- ---------------------------- 2.9/9.9 MB 322.6 kB/s eta 0:00:22
   ----------- ---------------------------- 2.9/9.9 MB 321.5 kB/s eta 0:00:22
   ----------- ---------------------------- 3.0/9.9 MB 321.5 kB/s eta 0:00:22
   ------------ --------------------------- 3.0/9.9 MB 321.6 kB/s eta 0:00:22
   ------------ --------------------------- 3.0/9.9 MB 321.6 kB/s eta 0:00:22
   ------------ --------------------------- 3.0/9.9 MB 319.5 kB/s eta 0:00:22
   ------------ --------------------------- 3.0/9.9 MB 320.6 kB/s eta 0:00:22
   ------------ --------------------------- 3.0/9.9 MB 320.6 kB/s eta 0:00:22
   ------------ --------------------------- 3.0/9.9 MB 317.9 kB/s eta 0:00:22
   ------------ --------------------------- 3.0/9.9 MB 318.5 kB/s eta 0:00:22
   ------------ --------------------------- 3.1/9.9 MB 318.6 kB/s eta 0:00:22
   ------------ --------------------------- 3.1/9.9 MB 318.1 kB/s eta 0:00:22
   ------------ --------------------------- 3.1/9.9 MB 318.1 kB/s eta 0:00:22
   ------------ --------------------------- 3.1/9.9 MB 316.6 kB/s eta 0:00:22
   ------------ --------------------------- 3.1/9.9 MB 317.2 kB/s eta 0:00:22
   ------------ --------------------------- 3.1/9.9 MB 317.2 kB/s eta 0:00:22
   ------------ --------------------------- 3.1/9.9 MB 317.3 kB/s eta 0:00:22
   ------------ --------------------------- 3.1/9.9 MB 317.3 kB/s eta 0:00:22
   ------------ --------------------------- 3.2/9.9 MB 314.4 kB/s eta 0:00:22
   ------------ --------------------------- 3.2/9.9 MB 314.4 kB/s eta 0:00:22
   ------------ --------------------------- 3.2/9.9 MB 314.0 kB/s eta 0:00:22
   ------------ --------------------------- 3.2/9.9 MB 315.0 kB/s eta 0:00:22
   ------------- -------------------------- 3.2/9.9 MB 315.1 kB/s eta 0:00:22
   ------------- -------------------------- 3.2/9.9 MB 314.2 kB/s eta 0:00:22
   ------------- -------------------------- 3.2/9.9 MB 314.2 kB/s eta 0:00:22
   ------------- -------------------------- 3.3/9.9 MB 314.8 kB/s eta 0:00:22
   ------------- -------------------------- 3.3/9.9 MB 313.9 kB/s eta 0:00:22
   ------------- -------------------------- 3.3/9.9 MB 314.9 kB/s eta 0:00:21
   ------------- -------------------------- 3.3/9.9 MB 314.0 kB/s eta 0:00:21
   ------------- -------------------------- 3.3/9.9 MB 314.1 kB/s eta 0:00:21
   ------------- -------------------------- 3.3/9.9 MB 314.1 kB/s eta 0:00:21
   ------------- -------------------------- 3.3/9.9 MB 312.7 kB/s eta 0:00:21
   ------------- -------------------------- 3.3/9.9 MB 312.8 kB/s eta 0:00:21
   ------------- -------------------------- 3.4/9.9 MB 312.9 kB/s eta 0:00:21
   ------------- -------------------------- 3.4/9.9 MB 312.5 kB/s eta 0:00:21
   ------------- -------------------------- 3.4/9.9 MB 311.7 kB/s eta 0:00:21
   ------------- -------------------------- 3.4/9.9 MB 311.3 kB/s eta 0:00:21
   ------------- -------------------------- 3.4/9.9 MB 311.8 kB/s eta 0:00:21
   ------------- -------------------------- 3.5/9.9 MB 312.3 kB/s eta 0:00:21
   -------------- ------------------------- 3.5/9.9 MB 312.9 kB/s eta 0:00:21
   -------------- ------------------------- 3.5/9.9 MB 312.9 kB/s eta 0:00:21
   -------------- ------------------------- 3.5/9.9 MB 312.1 kB/s eta 0:00:21
   -------------- ------------------------- 3.5/9.9 MB 312.2 kB/s eta 0:00:21
   -------------- ------------------------- 3.5/9.9 MB 313.1 kB/s eta 0:00:21
   -------------- ------------------------- 3.5/9.9 MB 313.1 kB/s eta 0:00:21
   -------------- ------------------------- 3.6/9.9 MB 312.3 kB/s eta 0:00:21
   -------------- ------------------------- 3.6/9.9 MB 311.1 kB/s eta 0:00:21
   -------------- ------------------------- 3.6/9.9 MB 310.3 kB/s eta 0:00:21
   -------------- ------------------------- 3.6/9.9 MB 311.2 kB/s eta 0:00:21
   -------------- ------------------------- 3.6/9.9 MB 310.9 kB/s eta 0:00:21
   -------------- ------------------------- 3.6/9.9 MB 311.8 kB/s eta 0:00:21
   -------------- ------------------------- 3.6/9.9 MB 311.8 kB/s eta 0:00:21
   -------------- ------------------------- 3.6/9.9 MB 310.2 kB/s eta 0:00:21
   -------------- ------------------------- 3.7/9.9 MB 310.3 kB/s eta 0:00:21
   -------------- ------------------------- 3.7/9.9 MB 310.9 kB/s eta 0:00:20
   -------------- ------------------------- 3.7/9.9 MB 310.9 kB/s eta 0:00:20
   -------------- ------------------------- 3.7/9.9 MB 310.9 kB/s eta 0:00:20
   --------------- ------------------------ 3.7/9.9 MB 309.8 kB/s eta 0:00:20
   --------------- ------------------------ 3.7/9.9 MB 309.8 kB/s eta 0:00:20
   --------------- ------------------------ 3.8/9.9 MB 311.2 kB/s eta 0:00:20
   --------------- ------------------------ 3.8/9.9 MB 311.2 kB/s eta 0:00:20

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: C:\Users\Admin\AppData\Local\spyder-6\python.exe -m pip install --upgrade pip

In [15]:
import pandas as pd 
import numpy as np

s = pd.Series() 
print("Pandas Series: ", s) 
data = np.array(['g', 'e', 'e', 'k', 's']) 
  
s = pd.Series(data) 
print("Pandas Series:\n", s)

Pandas Series:  Series([], dtype: object)
Pandas Series:
 0    g
1    e
2    e
3    k
4    s
dtype: str

In [16]:
import pandas as pd 
   
df = pd.DataFrame() 
print(df)
lst = ['Geeks', 'For', 'Geeks', 'is', 'portal', 'for', 'Geeks'] 
  
df = pd.DataFrame(lst) 
print(df)

Empty DataFrame
Columns: []
Index: []
        0
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks

In [29]:
import os 
print(os.getcwd())

C:\Users\Admin

In [4]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Admin\Downloads\PDA\data.csv")
print(df.head())

   Unnamed: 0   name  age     city category  sales  a   b
0           0   John   25    Delhi        A    200  5  10
1           1   Riya   22   Mumbai        B    120  2   3
2           2   Aman   30     Pune        A    250  7   8
3           3   Neha   27  Kolkata        C    300  4   6
4           4  Arjun   35   Jaipur        B    200  1   9

In [5]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  13 non-null     int64
 1   name        10 non-null     str
 2   age         13 non-null     int64
 3   city        10 non-null     str
 4   category    10 non-null     str
 5   sales       13 non-null     int64
 6   a           13 non-null     int64
 7   b           13 non-null     int64
dtypes: int64(5), str(3)
memory usage: 964.0 bytes
None

In [6]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Admin\Downloads\PDA\data.csv")
print(df.isnull().sum())
df = df.fillna(0)

Unnamed: 0    0
name          3
age           0
city          3
category      3
sales         0
a             0
b             0
dtype: int64

In [7]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Admin\Downloads\PDA\data.csv")
ages = df[df['age'] > 25]
print(ages)

    Unnamed: 0   name  age       city category  sales  a  b
2            2   Aman   30       Pune        A    250  7  8
3            3   Neha   27    Kolkata        C    300  4  6
4            4  Arjun   35     Jaipur        B    200  1  9
5            5    Jay   34  Bangalore        A    100  3  7
11          11  Arjun   35        NaN        B      0  1  9

In [8]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Admin\Downloads\PDA\data.csv")
df['total'] = df['a'] + df['b']
print(df.head())

   Unnamed: 0   name  age     city category  sales  a   b  total
0           0   John   25    Delhi        A    200  5  10     15
1           1   Riya   22   Mumbai        B    120  2   3      5
2           2   Aman   30     Pune        A    250  7   8     15
3           3   Neha   27  Kolkata        C    300  4   6     10
4           4  Arjun   35   Jaipur        B    200  1   9     10

In [9]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Admin\Downloads\PDA\data.csv")
res = df.groupby('category')['sales'].sum()
print(res)

category
A    650
B    440
C    300
Name: sales, dtype: int64

In [29]:
import pandas as pd 
df = pd.read_csv(r"C:\Users\Admin\Downloads\PDA\data.csv")
s = pd.Series([10, 20, 30, 40])

In [8]:
import pandas as pd 
df = pd.read_csv(r"C:\Users\Admin\Downloads\PDA\data.csv")
s = pd.Series([85, 90, 78], index=["A", "B", "C"])
s["A"]

np.int64(85)

In [9]:
import pandas as pd 
df = pd.read_csv(r"C:\Users\Admin\Downloads\PDA\data.csv")
s.iloc[0]
#access first element

np.int64(85)

In [27]:
import pandas as pd 
df = pd.read_csv(r"C:\Users\Admin\Downloads\PDA\data.csv")
s.mean(), s.max(), s.min()

(np.float64(25.0), np.int64(40), np.int64(10))

In [19]:
import pandas as pd 
df = pd.read_csv(r"C:\Users\Admin\Downloads\PDA\data.csv")
data={
    "Name":["Amit","Riya","Karan"],
    "Marks":[85,90,78]
}
df=pd.DataFrame(data)
df["Name"]

0     Amit
1     Riya
2    Karan
Name: Name, dtype: str

In [21]:
import pandas as pd 
df = pd.read_csv(r"C:\Users\Admin\Downloads\PDA\data.csv")
df.loc[0]
df.iloc[1]

Unnamed: 0         1
name            Riya
age               22
city          Mumbai
category           B
sales            120
a                  2
b                  3
Name: 1, dtype: object

In [21]:
import pandas as pd 
df = pd.read_csv(r"C:\Users\Admin\Downloads\PDA\data.csv")
data={
    "Name":["Amit","Riya","Karan"],
    "Marks":[85,90,78]
}
df=pd.DataFrame(data)
df["Grade"]=["A","A+","B"]
print(df)

    Name  Marks Grade
0   Amit     85     A
1   Riya     90    A+
2  Karan     78     B

In [20]:
import pandas as pd 
df = pd.read_csv(r"C:\Users\Admin\Downloads\PDA\data.csv")
data={
    "Name":["Amit","Riya","Karan"],
    "Marks":[85,90,78]
}
df=pd.DataFrame(data)
df[df["Marks"]>80]

   Name  Marks
0  Amit     85
1  Riya     90

In [18]:
import pandas as pd 
df = pd.read_csv(r"C:\Users\Admin\Downloads\PDA\data.csv")
df.describe()

       Unnamed: 0        age       sales          a          b
count    13.00000  13.000000   13.000000  13.000000  13.000000
mean      6.00000  19.615385  130.000000   2.692308   5.461538
std       3.89444  14.291830  112.398102   2.462540   3.843076
min       0.00000   0.000000    0.000000   0.000000   0.000000
25%       3.00000   0.000000    0.000000   1.000000   3.000000
50%       6.00000  25.000000  120.000000   2.000000   6.000000
75%       9.00000  30.000000  200.000000   4.000000   9.000000
max      12.00000  35.000000  300.000000   7.000000  10.000000